import { Fragment } from "react";

import type { Content } from "@/lib/content";
import { contactMailto, isDemoConfigured, LOGIN_URL } from "@/lib/site";
import { requestDemo } from "@/app/actions";

import { DemoForm } from "./demo-form";
import { GradualBlur } from "./gradual-blur";
import { ArrowDown, ArrowRight, Check, File } from "./icons";
import { LiveDemo } from "./live-demo";
import { ProductShot } from "./product-shot";
import { SiteHeader } from "./site-header";

export function LandingPage({ t }: { t: Content }) {
  return (
    <div lang={t.locale}>
      <a className="skip-link" href="#main">{t.nav.skipToContent}</a>
      <SiteHeader t={t} />

      <main id="main">
        {/* Hero — copy in a narrow column, the product shot bleeding wider beneath it. */}
        <section className="hero" aria-labelledby="hero-title">
          <div className="page-shell">
            <div className="hero-copy">
              <h1 id="hero-title">
                {t.hero.titleStart} <em>{t.hero.titleAccent}</em>
              </h1>
              <p className="lede">{t.hero.body}</p>
              <div className="hero-actions">
                <a href={LOGIN_URL} className="button button-dark">{t.hero.login}<ArrowRight /></a>
              </div>
            </div>
          </div>
          <div className="page-shell hero-shot">
            <ProductShot
              name="dashboard"
              title={t.shots.dashboard.title}
              caption={t.shots.dashboard.caption}
              alt={t.shots.dashboard.alt}
              priority
            />
          </div>
        </section>

        <section className="proof-strip">
          <div className="page-shell proof-inner">
            <p>{t.proof.label}</p>
            <ul className="proof-grid">
              {t.proof.items.map((item) => (
                <li key={item}><Check />{item}</li>
              ))}
            </ul>
          </div>
        </section>

        {/* The reporting-period runner. */}
        <section className="section runner-section" id="workflow">
          <div className="page-shell runner-layout">
            <div className="runner-copy">
              <h2>{t.liveDemo.title}</h2>
              <p className="lede">{t.liveDemo.body}</p>
            </div>
            <LiveDemo t={t} />
          </div>
        </section>

        <section className="section" id="product">
          <div className="page-shell">
            <div className="section-heading">
              <div>
                <h2>{t.attention.title}</h2>
              </div>
              <p>{t.attention.body}</p>
            </div>
            <div className="principle-grid">
              {t.attention.bullets.map((item, index) => (
                <article key={item}>
                  <span>0{index + 1}</span>
                  <h3>{item}</h3>
                </article>
              ))}
            </div>
          </div>
        </section>

        {/*
          The portfolio behind the screenshots.
          Labelled as a sample rather than dressed up as customers: the projects
          are generated by scripts/seed-portfolio.ts, and a strip of project
          names on a public page would read as a client list.
        */}
        <section className="section" id="portfolio">
          <div className="page-shell">
            <div className="section-heading">
              <div>
                <p className="micro-label">{t.portfolio.label}</p>
                <h2>{t.portfolio.title}</h2>
              </div>
              <p>{t.portfolio.body}</p>
            </div>
            <ul className="step-grid">
              {t.portfolio.items.map(([label, headline, body]) => (
                <li key={label}>
                  <span>{label}</span>
                  <h3>{headline}</h3>
                  <p>{body}</p>
                </li>
              ))}
            </ul>
            <p className="fine-print">{t.portfolio.note}</p>
          </div>
        </section>

        {/* AI-assisted import — the newest capability, and the one the old page never mentioned. */}
        <section className="section feature-section" id="import">
          <div className="page-shell feature-row">
            <div className="feature-copy">
              <h2>{t.ai.title}</h2>
              <p className="lede">{t.ai.body}</p>
              <dl className="feature-list">
                {t.ai.bullets.map(([title, body]) => (
                  <div key={title}>
                    <dt><Check />{title}</dt>
                    <dd>{body}</dd>
                  </div>
                ))}
              </dl>
              <p className="fine-print">{t.ai.note}</p>
            </div>
            <ProductShot
              name="import"
              title={t.shots.import.title}
              caption={t.shots.import.caption}
              alt={t.shots.import.alt}
              sizes="(max-width: 1000px) 200vw, 1200px"
            />
          </div>
        </section>

        <section className="section feature-section">
          <div className="page-shell feature-row" data-reverse>
            <div className="feature-copy">
              <h2>{t.progress.title}</h2>
              <p className="lede">{t.progress.body}</p>
              <dl className="stat-row">
                {t.progress.stats.map(([value, label], index) => (
                  <div key={label} data-danger={index === 2 || undefined}>
                    <dt>{value}</dt>
                    <dd>{label}</dd>
                  </div>
                ))}
              </dl>
            </div>
            <ProductShot
              name="progress"
              title={t.shots.progress.title}
              caption={t.shots.progress.caption}
              alt={t.shots.progress.alt}
              sizes="(max-width: 1000px) 200vw, 1200px"
            />
          </div>
        </section>

        <section className="section feature-section">
          <div className="page-shell feature-row">
            <div className="feature-copy">
              <h2>{t.baseline.title}</h2>
              <p className="lede">{t.baseline.body}</p>
            </div>
            <ProductShot
              name="boq"
              title={t.shots.boq.title}
              caption={t.shots.boq.caption}
              alt={t.shots.boq.alt}
              sizes="(max-width: 1000px) 200vw, 1200px"
            />
          </div>
        </section>


        {/*
          Questions immediately before the form: the last doubts get answered
          while the form is still the next thing on screen.

          Native <details>/<summary>: keyboard and screen-reader correct with no
          JS, which matters because this app ships no design-system runtime (see
          components/icons.tsx). The shared `name` makes it a real accordion in
          browsers that support it and independent panels in those that do not.
        */}
        <section className="section faq-section" id="faq" aria-labelledby="faq-title">
          <div className="page-shell">
            <div className="section-heading">
              <div>
                <p className="micro-label">{t.faq.label}</p>
                <h2 id="faq-title">{t.faq.title}</h2>
              </div>
            </div>
            <div className="faq-list">
              {t.faq.items.map(([question, answer]) => (
                <details key={question} name="faq">
                  <summary>{question}<ArrowDown /></summary>
                  <p>{answer}</p>
                </details>
              ))}
            </div>
          </div>
          {/* Built from the same array as the markup above, so the two cannot drift. */}
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                mainEntity: t.faq.items.map(([question, answer]) => ({
                  "@type": "Question",
                  name: question,
                  acceptedAnswer: { "@type": "Answer", text: answer },
                })),
              }),
            }}
          />
        </section>

        <section className="demo-section" id="demo">
          <div className="page-shell demo-layout">
            <div className="demo-copy">
              <h2>{t.demo.title}</h2>
              <p>{t.demo.body}</p>
              <div className="demo-sequence" aria-hidden>
                {t.demo.sequence.map((step, index) => (
                  <Fragment key={step}>
                    {index > 0 && <i />}
                    <span>{index === 0 && <File />}{step}</span>
                  </Fragment>
                ))}
              </div>
            </div>
            <DemoForm
              t={t}
              action={requestDemo}
              configured={isDemoConfigured()}
              mailtoHref={contactMailto(t.demo.mailSubject)}
            />
          </div>
        </section>
      </main>

      <GradualBlur />
    </div>
  );
}
